### PR TITLE
feat:user-auth-api

### LINKED ISSUE #12: [BK]: Add User Authentication (API)
> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Description
Implement an authentication mechanism for users, allowing login via wallet address and returning a signed JWT.

# Tasks
1. Create an `authenticateUser` service method in the `UserService`.
2. Add the `POST /auth/login` endpoint to accept wallet address and return a signed JWT token.
3. Write middleware to validate the token and attach user details to the request.
4. Document authentication flow in Swagger/OpenAPI.

# Example Service Implementation
```typescript
import jwt from 'jsonwebtoken';
import { User } from '../entities/User';
import { AppDataSource } from '../data-source';

const SECRET_KEY = process.env.JWT_SECRET || 'defaultSecret';

class AuthService {
  static async authenticate(walletAddress: string): Promise<string> {
    const userRepo = AppDataSource.getRepository(User);
    const user = await userRepo.findOne({ where: { walletAddress } });

    if (!user) {
      throw new Error('User not found');
    }

    return jwt.sign({ id: user.id, role: user.role }, SECRET_KEY, { expiresIn: '1h' });
  }
}
```

# Acceptance Criteria
- `POST /auth/login` accepts wallet address and returns a JWT token.
- Middleware validates the token and attaches user details to the request object.
- All tests pass with >80% code coverage.

---

### PR DESCRIPTION
**Pull request by zleypner**
# 🚀 StarShop Pull Request

**Closes #12**  
- Run formatting  
- Evidence attached  
- Commented the code  

---

## 📝 Changes Description

Implementing user authentication system with the following features:

- **Added** `authenticateUser` service method in `UserService`.
- **Created** new `POST /auth/login` endpoint for wallet-based authentication.
- **Implemented** JWT token generation and validation middleware.
- **Added** Swagger/OpenAPI documentation for the authentication flow.

### Implementation Highlights:
- **Uses** JWT for secure token generation with 1-hour expiration.
- **Validates** wallet addresses before authentication.
- **Includes** user role in JWT payload for authorization.
- **Environment-configurable** JWT secret key.

---

## 📸 Evidence
Pending

## ⏰ Time Spent Breakdown

The time spent on this task involved various stages of development, with some additional delays caused by resolving persistent errors, will be specified one the issue has been completed.

Overall, the task required more time than anticipated, as errors needed to be addressed systematically to ensure a robust and secure implementation.

- **Documentation**: Focused on detailed documentation to ensure clarity for future contributors, which required significant revisions.

## 🌌 Comments
Before reviewing this PR, please note:

- This implementation follows the Contributors Guide.
- JWT secret should be properly configured in production.
- Token expiration is set to 1 hour but can be adjusted based on requirements.
- Error handling follows project conventions with appropriate status codes.

### Acceptance Criteria to be Met:
- ✅ POST /auth/login endpoint implemented
- ✅ JWT token generation working
- ✅ Middleware validates tokens
- ✅ User details attached to request object

### CODE REVIEW

**Comment by zleypner** [comment]
> 🚧 **Work in Progress**: I am working on this issue and will update with implementation progress ASAP ⚡

**Comment by zleypner** [comment]
Hello @Villarley , I did an updated. I will wait for a feedback. I still need to continue and improve the method.

**Comment by Villarley** [comment]
> Hello @Villarley , I did an updated. I will wait for a feedback. I still need to continue and improve the method.

Hey Anwar, everything looks good when you finish please resolve conflicts. Great work🫡

**Comment by zleypner** [comment]
Hello @Villarley, thank you for the feedback! 
I am workin on finishing the improvements and will make sure to resolve any conflicts before wrapping up.

**Comment by zleypner** [comment]
Currently getting the following error. Once fixed, I will proceed to test end point properly with Postman. 

Error during Data Source initialization: AggregateError: 
    at internalConnectMultiple (node:net:1116:18)
    at afterConnectMultiple (node:net:1683:7) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED ::1:5432
        at createConnectionError (node:net:1646:14)
        at afterConnectMultiple (node:net:1676:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 5432
    },
    Error: connect ECONNREFUSED 127.0.0.1:5432
        at createConnectionError (node:net:1646:14)
        at afterConnectMultiple (node:net:1676:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 5432
    }
  ]
}

**Comment by zleypner** [comment]
Hello @Villarley ! 
🚧 I still have the same error mentioned previously. I have tried different work around. However the error persist.
I still trying to fix it in order to move forward.

**Comment by zleypner** [comment]
Hello there! Currently testing with postman. I will upload updates soon.

**Review by Villarley — APPROVED** [review]
LGTM!

**Pull request merged**
